# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-15 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20190614_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='marca',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventory.TipoEquipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Marca'),
        ),
    ]
