# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20190614_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='otroinventario',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventory.Empleado'),
            preserve_default=False,
        ),
    ]
