# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_otroinventario_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionImpresoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('Comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoAsignacion', models.BooleanField(default=True)),
                ('cod_empleadoEntrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EEntrega', to='Inventory.Empleado')),
                ('cod_empleadoRecibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ERecibe', to='Inventory.Empleado')),
            ],
        ),
        migrations.RemoveField(
            model_name='otroinventario',
            name='empleado',
        ),
        migrations.AddField(
            model_name='asignacionimpresoras',
            name='codigo_Inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.OtroInventario'),
        ),
    ]
