# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0009_auto_20190621_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('Comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoAsignacion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionImpresoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('Comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoAsignacion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioEmpleadoD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarioEmpleadoD', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioEmpleadoT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarioEmpleadoT', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioSalario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarioSalario', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=300)),
                ('Comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.ComentarioEmpleadoD')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=300)),
                ('Comentario', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoDuro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_empleado', models.CharField(max_length=6)),
                ('identidad', models.CharField(max_length=15)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('fechanacimiento', models.DateField()),
                ('estado', models.BooleanField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RTN', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadocivil', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_equipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_Caso', models.CharField(max_length=20)),
                ('Asunto', models.CharField(max_length=250)),
                ('Fecha_aperturaCaso', models.DateField()),
                ('Fecha_entregaProducto', models.DateField(blank=True, null=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradoacademico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_Inventario', models.CharField(max_length=11)),
                ('codigo_equipo', models.CharField(max_length=12)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('serial', models.CharField(max_length=50)),
                ('n_orden_compra', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.DiscoDuro')),
                ('empresaProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.EmpresaProveedor')),
                ('estado_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.EstadoEquipo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('causa_Falla', models.TextField()),
                ('accion_Realizar', models.TextField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Empleado')),
                ('codigo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.InventarioEquipo')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='OtroInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_Inventario', models.CharField(max_length=11)),
                ('serial', models.CharField(max_length=50)),
                ('n_orden_compra', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
                ('empresaProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.EmpresaProveedor')),
                ('estado_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.EstadoEquipo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='OtroMantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('causa_Falla', models.TextField()),
                ('accion_Realizar', models.TextField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Empleado')),
                ('codigo_Inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.OtroInventario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.EmpresaProveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesador', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=50)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Empleado')),
                ('gradoacademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.GradoAcademico')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fechaS', models.DateField()),
                ('comentarioSalario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.ComentarioSalario')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('Comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.ComentarioEmpleadoT')),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('Comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('EmpresaProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.EmpresaProveedor')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='otroinventario',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Regional'),
        ),
        migrations.AddField(
            model_name='marca',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.TipoEquipo'),
        ),
        migrations.AddField(
            model_name='inventarioequipo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Modelo'),
        ),
        migrations.AddField(
            model_name='inventarioequipo',
            name='procesador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Procesador'),
        ),
        migrations.AddField(
            model_name='inventarioequipo',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.RAM'),
        ),
        migrations.AddField(
            model_name='inventarioequipo',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Regional'),
        ),
        migrations.AddField(
            model_name='inventarioequipo',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.SistemaOperativo'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='codigo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.InventarioEquipo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estadocivil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.EstadoCivil'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Genero'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Regional'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direccionproveedor',
            name='EmpresaProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.EmpresaProveedor'),
        ),
        migrations.AddField(
            model_name='direccionempleado',
            name='Empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Empleado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cod_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Empleado'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Departamento'),
        ),
        migrations.AddField(
            model_name='asignacionimpresoras',
            name='cod_empleadoEntrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EEntrega', to='Inventory.Empleado'),
        ),
        migrations.AddField(
            model_name='asignacionimpresoras',
            name='cod_empleadoRecibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ERecibe', to='Inventory.Empleado'),
        ),
        migrations.AddField(
            model_name='asignacionimpresoras',
            name='codigo_Inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.OtroInventario'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cod_empleadoEntrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entrega', to='Inventory.Empleado'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cod_empleadoRecibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recibe', to='Inventory.Empleado'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='codigo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.InventarioEquipo'),
        ),
    ]
